In [1]:
import numpy as np


In [4]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [5]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a+a

array([ 2,  4,  6,  8, 10, 12])

In [8]:
type(a)

numpy.ndarray

In [9]:
np.array([5,6,4,7,8])

array([5, 6, 4, 7, 8])

In [10]:
b = ([1,2,3,4,5])
b

[1, 2, 3, 4, 5]

In [12]:
b+b

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]