#### LIMPIEZA DE DATASETS

In [8]:
import pandas as pd
RUTA = "C:\\Users\\WIN10\\Documents\\CERTIFICACION PYTHON\\DATASETS - CERTIFICACIÓN\\CARGA_CSV_VACUNACION.csv"

In [12]:
DATASET = pd.read_csv(RUTA)

In [15]:
DATASET.head()

country iso_code        date  total_vaccinations  people_vaccinated  \
0  Afghanistan      AFG  2021-02-22                 0.0                0.0   
1  Afghanistan      AFG  2021-02-23                 NaN                NaN   
2  Afghanistan      AFG  2021-02-24                 NaN                NaN   
3  Afghanistan      AFG  2021-02-25                 NaN                NaN   
4  Afghanistan      AFG  2021-02-26                 NaN                NaN   

   people_fully_vaccinated  daily_vaccinations_raw  daily_vaccinations  \
0                      NaN                     NaN                 NaN   
1                      NaN                     NaN              1367.0   
2                      NaN                     NaN              1367.0   
3                      NaN                     NaN              1367.0   
4                      NaN                     NaN              1367.0   

   total_vaccinations_per_hundred  people_vaccinated_per_hundred  \
0                             0.0                            0.0   
1                             NaN                            NaN   
2                             NaN                            NaN   
3                             NaN                            NaN   
4                             NaN                            NaN   

   people_fully_vaccinated_per_hundred  daily_vaccinations_per_million  \
0                                  NaN                             NaN   
1                                  NaN                            34.0   
2                                  NaN                            34.0   
3                                  NaN                            34.0   
4                                  NaN                            34.0   

                                            vaccines  \
0  Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...   
1  Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...   
2  Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...   
3  Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...   
4  Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...   

                 source_name            source_website  
0  World Health Organization  https://covid19.who.int/  
1  World Health Organization  https://covid19.who.int/  
2  World Health Organization  https://covid19.who.int/  
3  World Health Organization  https://covid19.who.int/  
4  World Health Organization  https://covid19.who.int/

In [14]:
DATASET.tail()

country iso_code        date  total_vaccinations  people_vaccinated  \
86507  Zimbabwe      ZWE  2022-03-25           8691642.0          4814582.0   
86508  Zimbabwe      ZWE  2022-03-26           8791728.0          4886242.0   
86509  Zimbabwe      ZWE  2022-03-27           8845039.0          4918147.0   
86510  Zimbabwe      ZWE  2022-03-28           8934360.0          4975433.0   
86511  Zimbabwe      ZWE  2022-03-29           9039729.0          5053114.0   

       people_fully_vaccinated  daily_vaccinations_raw  daily_vaccinations  \
86507                3473523.0                139213.0             69579.0   
86508                3487962.0                100086.0             83429.0   
86509                3493763.0                 53311.0             90629.0   
86510                3501493.0                 89321.0            100614.0   
86511                3510256.0                105369.0            103751.0   

       total_vaccinations_per_hundred  people_vaccinated_per_hundred  \
86507                           57.59                          31.90   
86508                           58.25                          32.38   
86509                           58.61                          32.59   
86510                           59.20                          32.97   
86511                           59.90                          33.48   

       people_fully_vaccinated_per_hundred  daily_vaccinations_per_million  \
86507                                23.02                          4610.0   
86508                                23.11                          5528.0   
86509                                23.15                          6005.0   
86510                                23.20                          6667.0   
86511                                23.26                          6874.0   

                                                vaccines         source_name  \
86507  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...  Ministry of Health   
86508  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...  Ministry of Health   
86509  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...  Ministry of Health   
86510  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...  Ministry of Health   
86511  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...  Ministry of Health   

                                          source_website  
86507  https://www.arcgis.com/home/webmap/viewer.html...  
86508  https://www.arcgis.com/home/webmap/viewer.html...  
86509  https://www.arcgis.com/home/webmap/viewer.html...  
86510  https://www.arcgis.com/home/webmap/viewer.html...  
86511  https://www.arcgis.com/home/webmap/viewer.html...

#### FORMA DEL DATASET 

In [16]:
DATASET.shape

(86512, 15)

In [18]:
len(DATASET)

86512

##### FILAS

In [23]:
DATASET.shape[1]

15

##### NOMBRE DE COLUMNAS

In [28]:
DATASET.columns

Index(['country', 'iso_code', 'date', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated',
       'daily_vaccinations_raw', 'daily_vaccinations',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'daily_vaccinations_per_million',
       'vaccines', 'source_name', 'source_website'],
      dtype='object')

In [29]:
DATASET.columns.values

array(['country', 'iso_code', 'date', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated',
       'daily_vaccinations_raw', 'daily_vaccinations',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred',
       'daily_vaccinations_per_million', 'vaccines', 'source_name',
       'source_website'], dtype=object)

In [30]:
DATASET.columns.tolist()

['country',
 'iso_code',
 'date',
 'total_vaccinations',
 'people_vaccinated',
 'people_fully_vaccinated',
 'daily_vaccinations_raw',
 'daily_vaccinations',
 'total_vaccinations_per_hundred',
 'people_vaccinated_per_hundred',
 'people_fully_vaccinated_per_hundred',
 'daily_vaccinations_per_million',
 'vaccines',
 'source_name',
 'source_website']

#### DETALLE DE LAS COLUMNAS NUMERICAS

In [33]:
DATASET.describe

<bound method NDFrame.describe of            country iso_code        date  total_vaccinations  \
0      Afghanistan      AFG  2021-02-22                 0.0   
1      Afghanistan      AFG  2021-02-23                 NaN   
2      Afghanistan      AFG  2021-02-24                 NaN   
3      Afghanistan      AFG  2021-02-25                 NaN   
4      Afghanistan      AFG  2021-02-26                 NaN   
...            ...      ...         ...                 ...   
86507     Zimbabwe      ZWE  2022-03-25           8691642.0   
86508     Zimbabwe      ZWE  2022-03-26           8791728.0   
86509     Zimbabwe      ZWE  2022-03-27           8845039.0   
86510     Zimbabwe      ZWE  2022-03-28           8934360.0   
86511     Zimbabwe      ZWE  2022-03-29           9039729.0   

       people_vaccinated  people_fully_vaccinated  daily_vaccinations_raw  \
0                    0.0                      NaN                     NaN   
1                    NaN                      NaN      

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4, 5, 6 ])

array([1, 2, 3, 4, 5, 6])

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a.size

6

In [7]:
a.ndim

1

In [9]:
a.dtype

dtype('int32')

In [10]:
a.shape

(6,)

In [15]:
a

array([1, 2, 3, 4, 5, 6])

In [14]:
a.tolist()

[1, 2, 3, 4, 5, 6]

In [16]:
a

array([1, 2, 3, 4, 5, 6])